src/ui/internal/components/Marker.tsx, src/ui/internal/modals/Challenge.tsx, src/ui/internal/modals/Refund.tsx
=> [bug] add missing tooltip for challenge period (Refund.tsx/Challenge.tsx)

src/ui/internal/modals/AddApproveArbitrator.tsx, src/ui/internal/modals/Arbitrate.tsx, src/ui/internal/notification/toast.ts
=> [Feature] improve toast handling

src/core/approveArbitrator.ts, src/core/approveSettlement.ts, src/core/arbitrate.ts, src/core/challenge.ts, src/core/claim.ts, src/core/claimMultiple.ts, src/core/offerSettlement.ts, src/core/pay.ts, src/core/refund.ts, src/core/release.ts, src/typing/index.ts, src/ui/internal/hooks/useModalCloseHandler.tsx, src/ui/internal/modals/AddApproveArbitrator.tsx, src/ui/internal/modals/ApproveSettlement.tsx, src/ui/internal/modals/Arbitrate.tsx, src/ui/internal/modals/Challenge.tsx, src/ui/internal/modals/Claim.tsx, src/ui/internal/modals/ClaimMultiple.tsx, src/ui/internal/modals/Pay.tsx, src/ui/internal/modals/Refund.tsx, src/ui/internal/modals/Release.tsx, src/ui/internal/modals/SettlementOffer.tsx
https://popstand.atlassian.net/browse/UN-1544
=> [UN-1544] add address as return for connected callbacks

src/ui/internal/components/Copy.tsx, src/ui/internal/modals/AddApproveArbitrator.tsx, src/ui/internal/modals/ApproveSettlement.tsx, src/ui/internal/modals/Arbitrate.tsx, src/ui/internal/modals/Challenge.tsx, src/ui/internal/modals/Claim.tsx, src/ui/internal/modals/ClaimMultiple.tsx, src/ui/internal/modals/Pay.tsx, src/ui/internal/modals/Refund.tsx, src/ui/internal/modals/Release.tsx, src/ui/internal/modals/SettlementOffer.tsx, src/ui/internal/notification/toast.ts, src/ui/render/pay.ts
=> [Feature] toast improvements

src/indexer/internal/queryClaimableEscrows.ts
https://popstand.atlassian.net/jira/software/projects/UN/boards/28?selectedIssue=UN-1567
=> SDK/Indexer: Challenged and expired payment returns as claimable

package.json, src/helpers/countdownChallengePeriod.ts, src/ui/internal/hooks/useAsync.ts, src/ui/internal/hooks/useCountdownChallengePeriod.tsx, src/ui/internal/modals/Challenge.tsx, src/ui/internal/modals/SettlementOffer.tsx, yarn.lock
only works with `swr` due to the need of having the escrowData updated (and to let the interval be aware of it with `useRef`)
=> fix the unsolvable!

src/ui/internal/modals/SettlementOffer.tsx
https://popstand.atlassian.net/browse/UN-1565
=> [UN-1565] fix close modal message for settlement

src/wallet/index.ts
https://popstand.atlassian.net/browse/UN-1506
=> [UN-1506] switchNetwork throws error iso of null if no wallet present

src/core/approveArbitrator.ts, src/core/arbitrate.ts, src/core/proposeArbitrator.ts, src/typing/index.ts, src/ui/internal/modals/AddApproveArbitrator.tsx, src/ui/internal/modals/Arbitrate.tsx, src/ui/internal/modals/Claim.tsx, src/ui/render/addApproveArbitrator.ts, src/ui/render/arbitrate.ts
https://popstand.atlassian.net/browse/UN-1539
=> [UN-1539] separate arbitration related types

src/core/__tests__/calculateAmounts.spec.ts, src/core/getTokenInfo.ts, src/helpers/__tests__/validPayment.test.tsx, src/helpers/validateAddress.ts, src/ui/internal/hooks/useAsync.ts, src/ui/internal/modals/Pay.tsx
https://popstand.atlassian.net/browse/UN-1594
Scenario 1 (modal opens):
Scenario 2 (modal doesn't open):
=> [UN-1594] No error message when tokenAddress is not a valid token

src/helpers/__tests__/validPayment.test.tsx, src/helpers/displayChallengePeriod.ts, src/ui/internal/modals/Pay.tsx
https://popstand.atlassian.net/browse/UN-1616
=> [UN-1616] add `useLongFormat` to displayChallengePeriod

src/helpers/__tests__/validPayment.test.tsx, src/ui/internal/modals/Release.tsx
https://popstand.atlassian.net/browse/UN-1612
=> [UN-1612] Release payment with modal: Error displayed after successful release

src/helpers/displayChallengePeriod.ts
https://popstand.atlassian.net/browse/UN-1636
=> [UN-1636] replace all 's' if there's only one from an unit

src/ui/internal/hooks/useCountdownChallengePeriod.tsx
https://popstand.atlassian.net/browse/UN-1634
=> [UN-1634] fix responsiveness of display of countdown

src/wallet/index.ts
https://popstand.atlassian.net/jira/software/projects/UN/boards/28?assignee=608827c0b233c8006b903a1e&selectedIssue=UN-1633
=> UN-1633 - fix the logic of connect function returning the walletAddress

src/helpers/getExchangeRates.ts, src/ui/internal/components/Amount.tsx, src/ui/internal/components/BalancesTable.tsx, src/ui/internal/components/ScopedModal.tsx, src/ui/internal/hooks/useAsync.ts, src/ui/internal/hooks/useCountdownChallengePeriod.tsx, src/ui/internal/hooks/useEscrowData.ts, src/ui/internal/hooks/useExchangeRates.ts, src/ui/internal/hooks/useModalCloseHandler.tsx, src/ui/internal/hooks/useSingleBalance.ts, src/ui/internal/hooks/useTokenInfo.ts, src/ui/internal/modals/AddApproveArbitrator.tsx, src/ui/internal/modals/ApproveSettlement.tsx, src/ui/internal/modals/Arbitrate.tsx, src/ui/internal/modals/Challenge.tsx, src/ui/internal/modals/Claim.tsx, src/ui/internal/modals/Pay.tsx, src/ui/internal/modals/Refund.tsx, src/ui/internal/modals/Release.tsx
- https://popstand.atlassian.net/jira/software/projects/UN/boards/28?assignee=608827c0b233c8006b903a1e&issueType=10046&selectedIssue=UN-1639
This PR does not fix not only the refund but release and other models too.
- https://popstand.atlassian.net/jira/software/projects/UN/boards/28?assignee=608827c0b233c8006b903a1e&issueType=10046&selectedIssue=UN-1613
- https://popstand.atlassian.net/jira/software/projects/UN/boards/28?assignee=608827c0b233c8006b903a1e&issueType=10046&selectedIssue=UN-1637
ps: 
- Creates custom hook or each fetcher using typescript
- Add comments "TODO" where we should improve the code
- replace useAsync hook with the hooks that were created.
- use refresh only in some screens
=> Fixes UN-1639, UN-1613 and UN-1637

src/ui/internal/modals/Challenge.tsx
https://popstand.atlassian.net/jira/software/projects/UN/boards/28?assignee=608827c0b233c8006b903a1e&selectedIssue=UN-1614
=> Challenge with modal: Display Close button after challenging

src/helpers/displayChallengePeriod.ts
https://popstand.atlassian.net/jira/software/projects/UN/boards/28?assignee=608827c0b233c8006b903a1e&selectedIssue=UN-1636
=> SDK - Pay using modal: Plural is displayed for single time units

src/typing/index.ts, src/ui/internal/hooks/useNetworkCheck.tsx, src/ui/internal/hooks/useWallet.ts, src/ui/internal/modals/Pay.tsx, src/ui/render/pay.ts
This lowers the number of displayed decimals in payment modal so that e.g. when converting USD to ETH rate it doesn't display 18 decimals
=> Lower decimals

src/indexer/getInstance.ts, src/indexer/internal/getClaimableEscrows.ts, src/indexer/internal/getPaymentList.ts, src/indexer/internal/getSinglePayment.ts, src/indexer/internal/getUserBalance.ts, src/indexer/internal/parseEscrowData.ts, src/indexer/internal/payload.ts, src/indexer/internal/queryBalance.ts, src/indexer/internal/queryBuilder.ts, src/indexer/internal/queryClaimableEscrows.ts, src/indexer/internal/types.ts, src/typing/index.ts
- chain id used as filter and returned from indexer
- fixed missing reference from indexer ata
=> Chain id indexer
